### ISSUE TITLE
get should work gracefully when the store is undefined

### ISSUE THREAD

**Issue by yherve** [ThaUnknown/simple-store-svelte#1]
(btw thanks for this library. It seems to be exactly what I was looking for)

Hi. I'am currently trying to replace the regular svelte store with your own and it seems the behaviour of 'get' is slightly different.
the original 'get' does not complain when the store is undefined, so I think that you should do the same.

sthg like that, I think:

``` js
Object.defineProperty(exports, 'get', {
  enumerable: true,
    get: function (store) {
      return store ? store.value: undefined
  }
})
```

**Comment by ThaUnknown** [comment]
the entire point of this library is to not use get so instead of doing `get(store)` you do `store.value`, but I'll fix it
